== Using Content Collections from Private Automation Hub in Automation Controller

. Navigate to pass:[<uri>https://hub.lab.example.com</uri>] and log in with the `admin` user name and the `redhat` password.
. Go to Collections -> Namespaces and click Create.
Enter `mike` in the `Name` field and then click `Create`.
. Click `Upload collection` and upload the `./mike-hello-1.0.0.tar.gz` archive.
+
[NOTE]
====
If you need to rebuild the collection, then change into the `./collections-source/mike/hello/` directory, update the `version` variable in the `galaxy.yml` file, and then run the `ansible-galaxy collection build` command.
====
. Go to Collections -> Approval and approve the uploaded collection.
. Install content collections needed by the `prep-for-testing.yml` playbook:
+
[subs="+quotes"]
----
[student@workstation collection-test]$ *ansible-galaxy collection install \*
> *-r collections/requirements.yml -p collections/*
----
. Run the `prep-for-testing.yml` playbook.
Enter `student` for the privilege escalation password.
+
[subs="+quotes"]
----
[student@workstation collection-test]$ *ansible-playbook prep-for-testing.yml -K*
----
+
The playbook likely fails when attempting to synchronize the projects.
. Navigate to pass:[<uri>https://controller.lab.example.com</uri>] and log in with the `admin` user name and the `redhat` password.
. Go to Resources -> Projects.
All added projects display a `Failed` status.
. Connect to `awx@controller`.
+
[subs="+quotes"]
----
[student@workstation collection-test]$ *ssh awx@controller*
----
. Change to the `/var/lib/awx/projects/` directory.
+
[subs="+quotes"]
----
[awx@controller ~]$ *cd /var/lib/awx/projects/*
----
. (Optional) For each of the projects `test-all`, `test-rh`, `test-published`, and `test-community`, you can change into the project directory and verify that the content collections can be installed locally.
+
[subs="+quotes"]
----
[awx@controller PROJECT]$ *ansible-galaxy collection install \*
> *-r collections/requirements.yml -p collections/*
----
+ Because all of the specified collections install without errors, this proves that controller trusts the web SSL certificate for pass:[<uri>https://hub.lab.example.com</uri>].
. Exit from `controller`.
[subs="+quotes"]
----
[awx@controller PROJECT]$ *exit*
----
. From the controller web UI, go to `Settings` and then `Jobs settings`.
Click `Edit` at the bottom of the page and then toggle the `Ignore Ansible Galaxy SSL Certificte Verification` so that it has a value of `On`.
Click `Save` at the bottom of the page.
. Go to Resources -> Projects and click the `Sync Project` icon for the `All Collections Project`, `Community Collections Project`, `Published Collections Project`, and `Red Hat Collections Project` projects.
All projects display a status of `Successful`.
+
[IMPORTANT]
====
If the projects continue to fail, update the `Hub: Community Collections`, `Hub: Published Collections`, and `Hub: Red{nbsp}Hat Certified Collections` credentials with a new API token.

From the private automation hub web UI, go to Collections -> API Token and then click `Load token`.
Copy the token.

From the automation controller web UI, got to Resources -> Credentials and edit each of the hub credentials.
Replace the `API Token` with the copied token and click `Save`.

Go to Resources -> Credentials and attempt the project synchronizations again.
====

== Using a Custom EE

The root cause for failure is that the control plane execution environment does not trust certificates signed by our classroom certificate authority.
This is the exact same issue that we experienced when trying to synchronize Git project repositories using HTTPS instead of SSH.

You can test this by building a new execution environment that includes our classroom certificates.

. Ensure that automation controller verifies Ansible galaxy SSL certificates.
From the controller web UI, go to `Settings` and then `Jobs settings`.
Click `Edit` at the bottom of the page and then toggle the `Ignore Ansible Galaxy SSL Certificte Verification` so that it has a value of `Off`.
Click `Save` at the bottom of the page.
. Change into the `custom-image` directory.
+
[subs="+quotes"]
----
[student@workstation collection-test]$ *cd custom-image/*
----
. Install content collections needed by the `create-custom-ee.yml` playbook:
+
[subs="+quotes"]
----
[student@workstation custom-image]$ *ansible-galaxy collection install \*
> *-r collections/requirements.yml -p collections/*
----
. Run the `create-custom-ee.yml` playbook.
This playbook creates a custom execution environment that includes our classroom certificates.
The playbook uploads the container image to pass:[<uri>https://hub.lab.example.com</uri>] and then pulls the image down to pass:[<uri>controller.lab.example.com</uri>].
The new image is tagged as `hub.lab.example.com/ee-supported-rhel8:2.0` (the name expected by the control plane execution environment).
Enter `student` for the privilege escalation password.
+
[subs="+quotes"]
----
[student@workstation custom-image]$ *ansible-playbook create-custom-ee.yml -K*
----
. From the automation controller web UI, got to Resources -> Credentials and attempt the project synchronizations again.
Even though SSL certificate verification is enabled, all projects succeed because the new control plane execution environment trusts the certificates signed by our classroom certificate authority.
