- name: Fail if mode is not defined
  fail:
    msg: The "mode" variable must be defined with a value of "add" or "remove".
  when: mode is not defined or (mode|lower != "add" and mode|lower != "remove")

- name: Fail if credential is not defined
  fail:
    msg: The "credential" variable must be defined.
  when: credential is not defined

- name: Add Prviate Automation Hub Collection credentials
  ansible.controller.credential:
    controller_host: "{{ controller_auth['host'] }}"
    controller_username: "{{ controller_auth['username'] }}"
    controller_password: "{{ controller_auth['password'] }}"
    validate_certs: false
    name: "{{ item['name'] }}"
    description: "{{ item['description'] | default(omit) }}"
    organization: "{{ item['organization'] | default('Default') }}"
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    inputs:
      url: "{{ item['url'] }}"
      auth_url: "{{ item['auth_url'] | default(omit) }}"
      token: "{{ hub_api_token }}"
    state: present
    update_secrets: "{{ item['update_secrets'] | default(False) }}"
  loop: "{{ credential }}"
  loop_control:
    label: "Adding Prviate Automation Hub Collection credential: {{ item.name }}"
  when: mode|lower == 'add'

- name: Remove Prviate Automation Hub Collection credentials
  ansible.controller.credential:
    controller_host: "{{ controller_auth['host'] }}"
    controller_username: "{{ controller_auth['username'] }}"
    controller_password: "{{ controller_auth['password'] }}"
    validate_certs: false
    name: "{{ item['name'] }}"
    credential_type: "Ansible Galaxy/Automation Hub API Token"
    state: absent
  loop: "{{ credential }}"
  loop_control:
    label: "Removing Prviate Automation Hub Collection credential: {{ item.name }}"
  when: mode|lower == 'remove'
