- name: Fail if mode is not defined
  fail:
    msg: The "mode" variable must be defined with a value of "add" or "remove".
  when: mode is not defined or (mode|lower != "add" and mode|lower != "remove")

- name: Fail if credential is not defined
  fail:
    msg: The "credential" variable must be defined.
  when: credential is not defined

- name: Associate Hub Credentials with an Organization
  ansible.controller.organization:
    controller_host: "{{ controller_auth['host'] }}"
    controller_username: "{{ controller_auth['username'] }}"
    controller_password: "{{ controller_auth['password'] }}"
    validate_certs: false
    name: "{{ item['organization'] | default('Default') }}"
    galaxy_credentials: "{{ credential | map(attribute='name') | list }}"
    state: present
  when: mode|lower == 'add'

- name: Remove Hub Credential Association with an Organization
  ansible.controller.organization:
    controller_host: "{{ controller_auth['host'] }}"
    controller_username: "{{ controller_auth['username'] }}"
    controller_password: "{{ controller_auth['password'] }}"
    validate_certs: false
    name: "{{ item['organization'] | default('Default') }}"
    galaxy_credentials:
      - "Ansible Galaxy"
    state: present
  when: mode|lower == 'remove'
