- name: Fail if mode is not defined
  fail:
    msg: The "mode" variable must be defined with a value of "add" or "remove".
  when: mode is not defined or (mode|lower != "add" and mode|lower != "remove")

- name: Fail if job_template is not defined
  fail:
    msg: The "job_template" variable must be defined.
  when: job_template is not defined

- name: Add Job Template
  ansible.controller.job_template:
    controller_host: "{{ controller_auth['host'] }}"
    controller_username: "{{ controller_auth['username'] }}"
    controller_password: "{{ controller_auth['password'] }}"
    validate_certs: false
    name: "{{ item['name'] }}"
    description: "{{ item['description'] | default(omit) }}"
    job_type: "{{ item['job_type'] | default('run') }}"
    inventory: "{{ item['inventory'] }}"
    project: "{{ item['project'] }}"
    execution_environment: "{{ item['execution_environment'] | default('Default execution environment') }}"
    playbook: "{{ item['playbook'] }}"
    credentials: "{{ item['credentials'] }}"
    labels: "{{ item['labels'] | default(omit) }}"
    extra_vars: "{{ item['extra_vars'] | default(omit) }}"
    forks: "{{ item['forks'] | default(omit) }}"
    limit: "{{ item['limit'] | default(omit) }}"
    verbosity: "{{ item['verbosity'] | default('0') }}"
    job_slice_count: "{{ item['job_slice_count'] | default('1') }}"
    timeout: "{{ item['timeout'] | default(omit) }}"
    ask_diff_mode_on_launch: "{{ item['ask_diff_mode_on_launch'] | default(omit) }}"
    instance_groups: "{{ item['instance_groups'] | default(omit) }}"
    job_tabs: "{{ item['job_tabs'] | default(omit) }}"
    skip_tags: "{{ item['skip_tags'] | default(omit) }}"
    become_enabled: "{{ item['become_enabled'] | default(omit) }}"
    host_config_key: "{{ item['host_config_key'] | default(omit) }}"
    allow_simultaneous: "{{ item['allow_simultaneous'] | default(omit) }}"
    use_fact_cache: "{{ item['use_fact_cache'] | default(omit) }}"
    survey_enabled: "{{ item['survey_enabled'] | default(omit) }}"
    start_at_task: "{{ item['start_at_task'] | default(omit) }}"
    scm_branch: "{{ item['scm_branch'] | default(omit) }}"
    ask_scm_branch_on_launch: "{{ item['ask_scm_branch_on_launch'] | default(omit) }}"
    state: present
  loop: "{{ job_template }}"
  loop_control:
    label: "Adding job template: {{ item['name'] }}"
  when: mode|lower == 'add'

- name: Remove Job Template
  ansible.controller.job_template:
    controller_host: "{{ controller_auth['host'] }}"
    controller_username: "{{ controller_auth['username'] }}"
    controller_password: "{{ controller_auth['password'] }}"
    validate_certs: false
    name: "{{ item['name'] }}"
    project: "{{ item['project'] }}"
    state: absent
  loop: "{{ job_template }}"
  loop_control:
    label: "Removing job template: {{ item['name'] }}"
  when: mode|lower == 'remove'
