- name: Fail if mode is not defined
  fail:
    msg: The "mode" variable must be defined with a value of "add" or "remove".
  when: mode is not defined or (mode|lower != "add" and mode|lower != "remove")

- name: Fail if credential is not defined
  fail:
    msg: The "credential" variable must be defined.
  when: credential is not defined

- name: Add machine credentials
  ansible.controller.credential:
    controller_host: "{{ controller_auth['host'] }}"
    controller_username: "{{ controller_auth['username'] }}"
    controller_password: "{{ controller_auth['password'] }}"
    validate_certs: false
    name: "{{ item['name'] }}"
    description: "{{ item['description'] }}"
    organization: "{{ item['organization'] | default('Default') }}"
    credential_type: Machine
    inputs:
      username: "{{ item['username'] | default(omit) }}"
      password: "{{ item['password'] | default(omit) }}"
      become_method: "{{ item['become_method'] | default(omit) }}"
      become_username: "{{ item['become_username'] | default(omit) }}"
      become_password: "{{ item['become_password'] | default(omit) }}"
      #ssh_key_data: "{{ lookup('file', '/home/student/.ssh/lab_rsa') }}"
    state: present
    update_secrets: "{{ item['update_secrets'] | default(False) }}"
  loop: "{{ credential }}"
  loop_control:
    label: "Adding machine credential: {{ item.name }}"
  when: mode|lower == 'add'

- name: Remove machine credentials
  ansible.controller.credential:
    controller_host: "{{ controller_auth['host'] }}"
    controller_username: "{{ controller_auth['username'] }}"
    controller_password: "{{ controller_auth['password'] }}"
    validate_certs: false
    name: "{{ item['name'] }}"
    credential_type: Machine
    state: absent
  loop: "{{ credential }}"
  loop_control:
    label: "Removing machine credential: {{ item.name }}"
  when: mode|lower == 'remove'
