- name: Fail if mode is not defined
  fail:
    msg: The "mode" variable must be defined with a value of "add" or "remove".
  when: mode is not defined or (mode|lower != "add" and mode|lower != "remove")

- name: Fail if credential is not defined
  fail:
    msg: The "credential" variable must be defined.
  when: credential is not defined

- name: Add SCM credentials
  ansible.controller.credential:
    controller_host: "{{ controller_auth['host'] }}"
    controller_username: "{{ controller_auth['username'] }}"
    controller_password: "{{ controller_auth['password'] }}"
    validate_certs: false
    name: "{{ item['name'] }}"
    description: "{{ item['description'] }}"
    organization: "{{ item['organization'] | default('Default') }}"
    credential_type: Source Control
    inputs:
      username: "{{ item['username'] | default(omit) }}"
      ssh_key_data: "{{ lookup('file', item['ssh_key_data'] ) }}"
    state: present
    update_secrets: "{{ item['update_secrets'] | default(False) }}"
  loop: "{{ credential }}"
  loop_control:
    label: "Adding source control credential: {{ item.name }}"
  when: mode|lower == 'add'

- name: Remove SCM credentials
  ansible.controller.credential:
    controller_host: "{{ controller_auth['host'] }}"
    controller_username: "{{ controller_auth['username'] }}"
    controller_password: "{{ controller_auth['password'] }}"
    validate_certs: false
    name: "{{ item['name'] }}"
    credential_type: Source Control
    state: absent
  loop: "{{ credential }}"
  loop_control:
    label: "Removing source control credential: {{ item.name }}"
  when: mode|lower == 'remove'
