---
- name: Test multiple collections
  hosts: servere.lab.example.com
  roles:
    - name: mike.hello.world

  post_tasks:
    - name: Create a prviate key
      community.crypto.openssl_privatekey:
        path: "/tmp/{{ ansible_facts['fqdn'] }}.key"
        mode: '400'
      register: create_private_key

    - name: Show create_private_key
      debug:
        var: create_private_key

    - name: Query controller for meta data
      ansible.controller.controller_meta:
      register: controller_meta_data

    - name: Show controller_meta_data
      debug:
        var: controller_meta_data
